#!/bin/bash

set -e

echo "================================"
echo "  Blog Platform Setup"
echo "================================"
echo ""

# Check for required commands
if ! command -v openssl &> /dev/null; then
    echo "Error: openssl is required but not installed."
    exit 1
fi

# Check if .env already exists
if [ -f .env ]; then
    read -p ".env file already exists. Overwrite? (y/N): " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
        echo "Setup cancelled."
        exit 0
    fi
fi

echo "This script will create your .env configuration file."
echo ""

# Admin credentials
echo "--- Admin Account ---"
read -p "Admin email [admin@example.com]: " admin_email
admin_email=${admin_email:-admin@example.com}

while true; do
    read -s -p "Admin password (min 8 characters): " admin_password
    echo ""
    if [ ${#admin_password} -ge 8 ]; then
        break
    fi
    echo "Password must be at least 8 characters."
done

# Database configuration
echo ""
echo "--- Database ---"
read -p "Database user [bloguser]: " db_user
db_user=${db_user:-bloguser}

read -s -p "Database password [auto-generate]: " db_password
echo ""
if [ -z "$db_password" ]; then
    db_password=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 16)
    echo "Generated database password."
fi

read -p "Database name [blog]: " db_name
db_name=${db_name:-blog}

# RustFS configuration
echo ""
echo "--- File Storage (RustFS) ---"
read -p "RustFS admin user [rustfsadmin]: " rustfs_user
rustfs_user=${rustfs_user:-rustfsadmin}

read -s -p "RustFS admin password [auto-generate]: " rustfs_password
echo ""
if [ -z "$rustfs_password" ]; then
    rustfs_password=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 16)
    echo "Generated RustFS password."
fi

read -p "S3 bucket name [blog-uploads]: " s3_bucket
s3_bucket=${s3_bucket:-blog-uploads}

# URLs
echo ""
echo "--- URLs ---"
read -p "Public URL [http://localhost:3000]: " public_url
public_url=${public_url:-http://localhost:3000}

read -p "S3 public URL [http://localhost:9000]: " s3_public_url
s3_public_url=${s3_public_url:-http://localhost:9000}

# Generate secrets
nextauth_secret=$(openssl rand -base64 32)

# Write .env file
cat > .env << EOF
# Generated by setup.sh on $(date)

# Database
DATABASE_URL=postgresql://${db_user}:${db_password}@db:5432/${db_name}
POSTGRES_USER=${db_user}
POSTGRES_PASSWORD=${db_password}
POSTGRES_DB=${db_name}

# RustFS (S3-compatible storage)
S3_ENDPOINT=http://rustfs:9000
S3_ACCESS_KEY=${rustfs_user}
S3_SECRET_KEY=${rustfs_password}
S3_BUCKET=${s3_bucket}
S3_PUBLIC_URL=${s3_public_url}
RUSTFS_ROOT_USER=${rustfs_user}
RUSTFS_ROOT_PASSWORD=${rustfs_password}

# NextAuth
NEXTAUTH_URL=${public_url}
NEXTAUTH_SECRET=${nextauth_secret}

# Admin Account
ADMIN_EMAIL=${admin_email}
ADMIN_PASSWORD=${admin_password}
EOF

echo ""
echo "================================"
echo "  Setup Complete!"
echo "================================"
echo ""
echo "Your .env file has been created."
echo ""
echo "Next steps:"
echo "  1. Start the services:"
echo "     docker compose -f docker-compose.dev.yml up --build"
echo ""
echo "  2. In another terminal, setup the database:"
echo "     docker compose exec web npx prisma db push"
echo "     docker compose exec web npm run db:seed"
echo ""
echo "  3. Open http://localhost:3000"
echo "     Login: ${admin_email}"
echo ""
